name: "Telegram Report Bot"
version: "1.0"
slug: "telegram_report_bot"
description: "Telegram bot to collect and report production data"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
homeassistant_api: false
stdin: false
hassio_api: false
host_network: true
options: {}
schema: {}